name: CD Vollmed

on:
  push:
    branches: ["main"]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build da imagem
      run: docker build -t vollmed-api_api:latest .

    - name: Roda Docker Compose
      run: docker compose up -d

    - name: Deploy para EC2
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USERNAME }}
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        PORT: ${{ secrets.PORT }}
      run: | 
         echo "$EC2_PRIVATE_KEY" > deploy_key.pem
         chmod 600 deploy_key.pem
         docker save -o vollmed-api.tar vollmed-api_api:latest
         scp -o StrictHostKeyChecking=no -i deploy_key.pem vollmed-api.tar $USER@$HOST:/home/ubuntu/
         scp -o StrictHostKeyChecking=no -i deploy_key.pem init.sql $USER@$HOST:/home/ubuntu/
         scp -o StrictHostKeyChecking=no -i deploy_key.pem docker-compose-prod.yaml $USER@$HOST:/home/ubuntu/
         scp -o StrictHostKeyChecking=no -i deploy_key.pem script-deploy.sh $USER@$HOST:/home/ubuntu/
         
         ssh -i deploy_key.pem $USER@$HOST "chmod +x script-deploy.sh && ./script-deploy.sh"

         
